# Generated by Django 4.2.6 on 2023-11-25 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_reviewrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewrating',
            old_name='ratings',
            new_name='rating',
        ),
    ]
